apiVersion: apps/v1
kind: Deployment
metadata:
  name: lam
  namespace: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lam
  template:
    metadata:
      labels:
        app: lam
    spec:
      containers:
      - name: lam
        image: ldapaccountmanager/lam:stable
        ports:
        - containerPort: 80
        env:
        - name: LDAP_SERVER
          value: "ldap://openldap.ldap.svc.cluster.local:389"
        - name: LDAP_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: openldap-config
              key: DOMAIN
        - name: LDAP_BASE_DN
          valueFrom:
            configMapKeyRef:
              name: openldap-config
              key: BASE_DN
        - name: LDAP_USERS_DN
          valueFrom:
            configMapKeyRef:
              name: openldap-config
              key: BASE_DN
        - name: LDAP_GROUPS_DN
          valueFrom:
            configMapKeyRef:
              name: openldap-config
              key: BASE_DN
        - name: LDAP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openldap-credentials
              key: LDAP_ADMIN_PASSWORD
        - name: LAM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openldap-credentials
              key: LAM_PASSWORD
